apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: my-container
          image: sharmila79/docker-python-helloworld:${VERSION}
          ports:
            - containerPort: 8080
